### PR TITLE
Add wasm - webassembly synonym group

### PR DESCRIPTION
**Pull request by kamilogorek**
https://github.com/getsentry/sentry-docs/pull/2923

### CODE REVIEW

**Comment by kamilogorek** [comment]
Bump @cameronmcefee

**Comment by cameronmcefee** [comment]
Not sure how I missed this. Sorry!

**Comment by cameronmcefee** [comment]
@kamilogorek this appears to be working now

**Comment by kamilogorek** [comment]
Lovely, thanks!

**Pull request merged**
